// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRiWLFQFrQSi6ZJ1El5wceZX5WwKZp4_4',
    appId: '1:429145076753:web:48229dac324fbde2c9edb0',
    messagingSenderId: '429145076753',
    projectId: 'houseofhope-df698',
    authDomain: 'houseofhope-df698.firebaseapp.com',
    storageBucket: 'houseofhope-df698.firebasestorage.app',
    measurementId: 'G-N6YC32CT45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx2BOh4jXdRq7z5uOjL5i0o2syEE_EE-E',
    appId: '1:429145076753:android:f9d0ab8daed5dbe4c9edb0',
    messagingSenderId: '429145076753',
    projectId: 'houseofhope-df698',
    storageBucket: 'houseofhope-df698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQR0w9WRDNB9AD7WJUYGDExC16l9y6JBo',
    appId: '1:429145076753:ios:0d1e6fa1fb37976ac9edb0',
    messagingSenderId: '429145076753',
    projectId: 'houseofhope-df698',
    storageBucket: 'houseofhope-df698.firebasestorage.app',
    iosBundleId: 'com.example.houseofhope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQR0w9WRDNB9AD7WJUYGDExC16l9y6JBo',
    appId: '1:429145076753:ios:0d1e6fa1fb37976ac9edb0',
    messagingSenderId: '429145076753',
    projectId: 'houseofhope-df698',
    storageBucket: 'houseofhope-df698.firebasestorage.app',
    iosBundleId: 'com.example.houseofhope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRiWLFQFrQSi6ZJ1El5wceZX5WwKZp4_4',
    appId: '1:429145076753:web:2f965505a57ec98ac9edb0',
    messagingSenderId: '429145076753',
    projectId: 'houseofhope-df698',
    authDomain: 'houseofhope-df698.firebaseapp.com',
    storageBucket: 'houseofhope-df698.firebasestorage.app',
    measurementId: 'G-925G58NLM7',
  );
}
